name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint + Fix with eslint
        run: npx eslint ./ --fix